### ISSUE TITLE
GitLab package uploads don't seem to be working

### ISSUE THREAD

**Issue by jamietanna** [go-semantic-release/hooks-goreleaser#2]
Releases to GitLab Package Registry, when configured with a "Project Access Token" (`api`, `write_repository`, `write_registry`), do not seem to be occuring. The Release in GitLab is updated, but no changes appear in the Package Registry

Repo: https://gitlab.com/tanna.dev/dmd-go-semver

```json
{
  "plugins": {
    "commit-analyzer": {
      "name": "default@^1.11.0"
    },
    "ci-condition": {
      "name": "default"
    },
    "changelog-generator": {
      "name": "default",
      "options": {
        "emojis": "true"
      }
    },
    "provider": {
      "name": "gitlab",
      "options": {
        "gitlab_projectid": "44435308"
      }
    }
  }
}
```

Goreleaser config:

```yaml
# ...
gitlab_urls:
  use_package_registry: true
```

Example build that isn't publishing: https://gitlab.com/tanna.dev/dmd-go-semver/-/jobs/3960632267

**Comment by christophwitzko** [comment]
Hmm, I am not sure what is causing this. Here is a working example of `go-semantic-release` on GitLab: https://gitlab.com/go-semantic-release/example-go-application

Maybe this helps ☺️

**Comment by jamietanna** [comment]
Sorry, just coming back to this - do you know how the `GITLAB_TOKEN` for :point_up: was defined? Is it a https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html or a per-user Personal Access Token?

**Comment by jamietanna** [comment]
Interestingly, with https://gitlab.com/tanna.dev/dmd-go-semver/-/releases/v1.3.2 (no longer setting `use_package_registry` and using a Project Access Token) I still don't see artifacts uploaded :thinking:

**Comment by christophwitzko** [comment]
I created a Personal Access Token for this project with the `api` scope.

**Comment by jamietanna** [comment]
Interesting. I've just tried https://gitlab.com/tanna.dev/dmd-go-semver/-/releases/v1.3.3 (using a Personal Access Token with `api` and a few other scopes) and that has _not_ uploaded anything to the release :thinking:

**Comment by jamietanna** [comment]
Looks like there may have been some config issues in my `.goreleaser.yaml` :upside_down_face: 

Just retrying with a more realistic config, then will see if the Project vs Personal Access Token is coming into play at all

**Comment by jamietanna** [comment]
OK, yep, this looks like complete user error, on the side of my `.goreleaser.yaml` config being a bit suspicious! 

Thanks for the help diagnosing it!
