### ISSUE TITLE
Update goreleaser source (after next release)

### ISSUE THREAD

**Issue by jamietanna** [go-semantic-release/hooks-goreleaser#7]
This is a tracking issue just to cover updating Goreleaser's code to the latest version, as it includes fixes like https://github.com/goreleaser/goreleaser/pull/4555

**Comment by jamietanna** [comment]
Looks like https://github.com/goreleaser/goreleaser/releases/tag/v1.24.0 is now the latest release - @christophwitzko is it documented how to do the updates? I'm happy to raise a PR!

**Comment by jamietanna** [comment]
I've tried with #8:

- Checkout https://github.com/goreleaser/goreleaser/releases/tag/v1.24.0
- Copy all files from :point_up: into `goreleaser/`

**Comment by christophwitzko** [comment]
Hi @jamietanna,

thanks for looking into this. These are the following steps I perform to update the goreleaser depenceny:
1. Change the `github.com/goreleaser/goreleaser` version in the `go.mod` file
2. Run `./scripts/fork-goreleaser.sh`
3. `git add goreleaser` and `git commit`

**Comment by christophwitzko** [comment]
https://github.com/go-semantic-release/hooks-goreleaser/releases/tag/v1.10.0 contains now the GoReleaser v1.24.0

**Comment by jamietanna** [comment]
Thanks very much, that's good to know for the future :raised_hands:
